### ISSUE TITLE
Is there a mirror for ubuntu18?

### ISSUE THREAD

**Issue by MengAjin** [radxa-build/rock-3a#1]
Is there a mirror for ubuntu18? and with pre-built rknn-toolkit?

**Comment by RadxaYuntian** [comment]
We no longer provide Ubuntu 18 image. You can, however, modify our [tool](https://github.com/radxa/debos-radxa/blob/65110dddca920320ed9e26729a29bb4159e126c0/configs/boards/rk3568/config-rock-3a-ubuntu-focal-server-arm64-gpt.sh#L14) to build a custom image for yourself. This is not supported though.
