### ISSUE TITLE
烧录ubuntu系统无法进入桌面

### ISSUE THREAD

**Issue by guangjieMVP** [radxa-build/rock-3a#10]
烧录：
![image](https://github.com/radxa-build/rock-3a/assets/43517324/f835aef4-6391-43ab-bc37-568b3004249e)
错误：
![6dedb0e8b8d24269e62279e7e4d6cd7](https://github.com/radxa-build/rock-3a/assets/43517324/4908b6bf-3231-4881-9a4a-bd4454097779)

**Comment by guangjieMVP** [comment]
debian系统是可以的，无桌面系统的ubuntu也是可以的

**Comment by RadxaYuntian** [comment]
我们目前只支持Debian桌面系统。我们之后会移除不支持的系统。
