### ISSUE TITLE
Request: Fully Preemptible Kernel (RT) Image Version for CLI

### ISSUE THREAD

**Issue by keypunch416** [radxa-build/rock-3a#3]
This is a request and not a bug.

Request is for CLI version added to the RBUILD using standard Kernel Fully Preemptive Kernel (RT) option.  So far my research indicates the kconfig option is PREEMPT_RT. 

Research has indicated as of Version 5.10 of the vanilla Linux Kernel can be configured as a low-latency version as the mainline Kernel has accepted multiple merge requests from the Preempt-rt patch team.

This request is not for the Preempt-rt patches to be applied to the standard Linux Kernel.  Just to enable the kconfig option PREEMPT_RT that the standard Linux Kernel has.

**Comment by keypunch416** [comment]
Issue #4 "Request: Linux Kernel with No Debug Data/Information" should be considered as required for this request.

**Comment by keypunch416** [comment]
I just discovered Debian has linux-image-rt-arm64 packages.

**Comment by RadxaYuntian** [comment]
Currently ROCK 3A uses Rockchip vendor kernel, which makes applying mainline patches difficult.
