### ISSUE TITLE
ubuntu server can't be updated because og NO PUBKEY error

### ISSUE THREAD

**Issue by easy-and-simple** [radxa-build/rock-3a#5]
Get:1 http://apt.radxa.com/focal-stable focal InRelease [2359 B]
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
Hit:5 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
Err:1 http://apt.radxa.com/focal-stable focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9B98116C9AA302C7
Reading package lists... Done
W: GPG error: http://apt.radxa.com/focal-stable focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9B98116C9AA302C7
E: The repository 'http://apt.radxa.com/focal-stable focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by RadxaYuntian** [comment]
This is a known issue, since our current image contains an expired APT keyring. We are planning to release a new Beta image for ROCK 3A early June, which will contain the updated system and the current keyring.

**Comment by easy-and-simple** [comment]
Would you make the new image to meets RKNN requirements, because now RKNN is not working?

**Comment by RadxaYuntian** [comment]
RKNN is currently unsupported. This will be a new feature request that we can develop later. Currently the focus is to update systems for existing products.

**Comment by RadxaYuntian** [comment]
@maycides Please add this to our to-do list.

**Comment by easy-and-simple** [comment]
Guys could you tell me whey I get following error? I installed rknn-toolkit2 and copied in /usr/bin correct version of librknnrt.so. Tried it on different linix builds including Debian and Ubuntu, server and desktop but it always fail with this error.

`rock@rock-3a:~/rknn-toolkit2/rknn_toolkit_lite2/examples/inference_with_lite$ python3 test.py
--> Load RKNN model
done
--> Init runtime environment
E RKNN: [11:06:04.233] failed to open rknpu module, need to insmod rknpu dirver!
E RKNN: [11:06:04.233] failed to open rknn device!
E Catch exception when init runtime!
E Traceback (most recent call last):
  File "/home/rock/.local/lib/python3.9/site-packages/rknnlite/api/rknn_lite.py", line 148, in init_runtime
    self.rknn_runtime.build_graph(self.rknn_data, self.load_model_in_npu)
  File "rknnlite/api/rknn_runtime.py", line 840, in rknnlite.api.rknn_runtime.RKNNRuntime.build_graph
Exception: RKNN init failed. error code: RKNN_ERR_FAIL

Init runtime environment failed`

**Comment by easy-and-simple** [comment]
I solved it. Issue was caused by newer kernel image I installed
