### ISSUE TITLE
GPU VPU not working

### ISSUE THREAD

**Issue by easy-and-simple** [radxa-build/rock-3a#6]
Guys GPU and VPU of the ROCK-3A board don't work and graphic and video processings are performed on CPU that is highly loaded and at very low framerate
Seeed Studio claims that their device based on RK3568 model LinkStar-H68K supports GPU and VPU accelerations and supports 4K@60fps H.265/H.264/VP9 video decoding and 1080@60fps H.265/H.264 video encoding
I tried to run images for LinkStar-H68K on ROCK-3A but without success.
Could you integrate video acceleration in RCK-3A images or help me to run LinkStar-H68K images on my ROCK-3A?

**Comment by RadxaYuntian** [comment]
For video acceleration please check the [latest test build](https://github.com/radxa-build/rock-3a/releases/tag/test-build-1). For GPU Rockchip SDK supports OpenGL-ES only. We plan to support Panfrost in a later date which support OpenGL. In the mean time you can try gl4es, and [here is a guide](https://forum.radxa.com/t/guide-run-minecraft-at-full-speed-on-rock-5b/11937) for ROCK 5B that could be applied to 3A as well.

We do not support 3rd party images.
